#!/usr/bin/env python3
"""Emit LaTeX tables straight from results/tables so the paper can never
drift from the numbers the code actually produced."""
import sys
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
TAB = ROOT / "results" / "tables"
OUT = ROOT / "paper" / "generated_tables.tex"


def tex(df, caption, label, fmt=None, col=None):
    body = df.to_latex(index=False, escape=False, float_format=fmt or "%.3f",
                       column_format=col or "l" * len(df.columns))
    body = body.replace("\\toprule", "\\hline").replace("\\midrule", "\\hline") \
               .replace("\\bottomrule", "\\hline")
    return (f"\\begin{{table}}[t]\n\\centering\n\\small\n"
            f"\\caption{{{caption}}}\n\\label{{{label}}}\n"
            f"\\resizebox{{\\columnwidth}}{{!}}{{%\n{body}}}\n"
            f"\\end{{table}}\n\n")


def main():
    out = ["% GENERATED by scripts/make_paper_tables.py -- do not edit by hand\n\n"]

    d = pd.read_csv(TAB / "01_model_footprints.csv")
    d = d[["model", "total_params_B", "active_params_B", "n_experts", "top_k",
           "expert_MB", "routed_expert_GB", "expert_frac"]]
    d.columns = ["Model", "Total (B)", "Active (B)", "$E$", "$k$",
                 "Expert (MB)", "Pool (GB)", "Expert frac."]
    out.append(tex(d, "Expert weights dominate every checkpoint studied. "
                      "Total and active parameter counts reproduce the "
                      "published figures, which validates the footprint model.",
                   "tab:footprint", "%.2f"))

    d = pd.read_csv(TAB / "02_capacity_gain.csv")
    d = d[d.expansion == "hbm_cxl_local"][
        ["model", "total_GB", "gpus_hbm_only", "gpus_with_cxl", "gpu_reduction"]]
    d.columns = ["Model", "Weights (GB)", "GPUs, HBM only",
                 "GPUs, +512\\,GB CXL", "Reduction"]
    out.append(tex(d, "GPUs required purely to hold the weights, with and "
                      "without direct-attached CXL expansion per GPU.",
                   "tab:capacity", "%.1f"))

    d = pd.read_csv(TAB / "05_batch_regime.csv")
    p = d.pivot(index="batch_size", columns="model",
                values="coverage_frac").reset_index()
    p.columns.name = None
    p = p.rename(columns={"batch_size": "Batch"})
    out.append(tex(p, "Fraction of experts touched per layer per batch. Past a "
                      "few hundred tokens the batch touches everything, and the "
                      "HBM tier stops behaving like a cache.",
                   "tab:coverage", "%.3f"))

    d = pd.read_csv(TAB / "10_critical_batch.csv")
    d = d[d.target_overhead == 0.10].pivot(
        index="expert_hit_rate", columns="model",
        values="critical_batch_tokens").reset_index()
    d.columns.name = None
    d = d.rename(columns={"expert_hit_rate": "$h$"})
    out.append(tex(d, "Critical batch size $B^\\ast$ in tokens at "
                      "$\\varepsilon=10\\%$. The hit rate is the only lever "
                      "that moves it by orders of magnitude.",
                   "tab:critical", "%.0f"))

    d = pd.read_csv(TAB / "09_crossover.csv")
    d = d[d.target_resident_frac.isin([0.90, 0.99])]
    p = d.pivot_table(index="batch_size", columns=["model", "target_resident_frac"],
                      values="overhead")
    p = p.reset_index()
    p.columns = ["Batch"] + [f"{m.split('-')[0]} {int(r*100)}\\%"
                             for m, r in p.columns[1:]]
    out.append(tex(p, "Measured stall overhead (fraction of compute) against "
                      "batch size, at 90\\% and 99\\% expert residency.",
                   "tab:crossover", "%.3f"))

    d = pd.read_csv(TAB / "11_prefetch_sweep.csv")
    base = d[d.prefetch_width == 0].set_index("model").overhead.to_dict()
    d = d[(d.prefetch_width.isin([0.10, 0.25]))][
        ["model", "prefetch_depth", "prefetch_width", "prefetch_coverage",
         "overhead"]]
    d["baseline"] = d.model.map(base)
    d.columns = ["Model", "Depth", "Width", "Coverage", "Overhead", "No prefetch"]
    out.append(tex(d, "Speculative prefetch of the head of the cold tail, at "
                      "90\\% residency and batch 2048. Deeper lookahead widens "
                      "the transfer window linearly.",
                   "tab:prefetch", "%.3f"))

    d = pd.read_csv(TAB / "12_skew_sensitivity.csv")
    d = d[["zipf_s", "batch_size", "hit_rate", "expert_hit_rate", "overhead"]]
    d.columns = ["$s$", "Batch", "Routing hit", "Fetch hit", "Overhead"]
    out.append(tex(d, "Sensitivity to router skew, Qwen3-235B at 50\\% "
                      "residency. At $s=0$ tiering buys exactly its capacity "
                      "fraction and nothing more.",
                   "tab:skew", "%.3f"))

    d = pd.read_csv(TAB / "13_bandwidth_sensitivity.csv")
    d = d[["model", "cxl_bw_gbs", "extrapolated", "overhead"]]
    d.columns = ["Model", "CXL GB/s", "Extrapolated", "Overhead"]
    out.append(tex(d, "Bandwidth sensitivity at 95\\% residency, batch 2048. "
                      "Points above 52\\,GB/s are outside the published "
                      "measured range and are marked as extrapolated.",
                   "tab:bandwidth", "%.3f"))

    OUT.write_text("".join(out), encoding="utf-8")
    print(f"wrote {OUT} ({len(out)-1} tables)")


if __name__ == "__main__":
    main()
